BORROWING_PERIOD_DAYS = 14
MAX_ACTIVE_BORROWINGS = 5

FINE_FIRST_PERIOD_DAYS = 7
FINE_FIRST_PERIOD_RATE = 1.0
FINE_AFTER_FIRST_PERIOD_RATE = 2.0

PASSWORD_MIN_LENGTH = 8
PASSWORD_MAX_LENGTH = 128
PASSWORD_HASH_ITERATIONS = 600_000